version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      DB_DIALECT: MYSQL
      DB_URL: jdbc:mysql://db:3306/lavagna?autoReconnect=true&useSSL=false
      DB_USER: lavagna
      DB_PASS: lavagna_password
      SPRING_PROFILE: dev
    depends_on:
      - db
    networks:
      - backend
      - frontend
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna
      MYSQL_PASSWORD: lavagna_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/main/webapp:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - frontend

volumes:
  db_data:

networks:
  backend:
    name: backend_network 
  frontend:
    name: frontend_network  

